#! /bin/sh

[ `id -u` != 0 ] && exit 0

tempfile=`mktemp 2> /dev/null` || tempfile=/tmp/tmpfile$$
trap "rm -f $tempfile" 0 1 2 5 15

if [ ! -e /var/lib/instpkg/xsession.props ]; then
    ls /etc/X11/xinit.d /etc/X11/xresources.d > /var/lib/instpkg/xsession.props 2> /dev/null
    exit 0
fi

ls /etc/X11/xinit.d /etc/X11/xresources.d > $tempfile 2> /dev/null

if ! cmp $tempfile /var/lib/instpkg/xsession.props > /dev/null 2>&1; then
    mv $tempfile /var/lib/instpkg/xsession.props
    if [ -x /usr/bin/infodlg ]; then
	start-stop-daemon -S -b -x msgx "Environment has changed - re-login to activate changes"
    else
	logger "Environment has changed - re-login to activate changes"
    fi
fi
