#! /bin/sh

#/bin/_file_end_linefeed.sh
#_mkcpio

CREATEDIRS="\
etc/pam.d \
etc/profile.d \
etc/init.d \
etc \
bin \
sbin \
lib \
usr/share/doc \
usr/share/man \
usr/share/info \
usr/share \
usr/bin \
usr/sbin \
usr/lib \
usr/include \
usr \
var/cache \
var/lib \
var/lock \
var/log \
var/spool \
var \
"

PKG=$3

###overwrite
[ "$PKG" = "gcc-tgt" ] && PKG=gcc
[ "$PKG" = "glibc-tgt" ] && PKG=glibc
###overwrite

DONTINSTALL=" skeleton toolchain toolchain-external toolchain-external-custom initscripts jpeg busybox coreutils "
DONTINSTALL2=" getent jpeg toolchain-external toolchain-external-custom "

echo "$DONTINSTALL2" | grep -q " $PKG " && exit 0

DIRSCRIPT=$(cd $(dirname "$0") && pwd -P)
echo "***********"
pwd -P
echo "***********"

DESTROOT=output/target
BUILDROOT=output/build
PKGDEST=/dest
retval=0
echo "###### PKG_SCRIPT $PKG $(cat $BUILDROOT/build-sysinit.log) $1 $2"

if [ "$1" = "start" ] && [ "$2" = "install-target" -o "$2" = "install-staging" ]; then

    [ -e $BUILDROOT/inst_start.log ] && exit 0
    touch $BUILDROOT/inst_start.log

    rm -rf $DESTROOT/*

    for i in $CREATEDIRS; do
	mkdir -p $DESTROOT/$i
    done
    ln -sf share/doc $DESTROOT/usr/doc
    ln -sf share/man $DESTROOT/usr/man
    ln -sf share/info $DESTROOT/usr/info
    ln -sf lib $DESTROOT/usr/lib64
    ln -sf lib $DESTROOT/lib64

    [ -e _scripts/$PKG.inst_start.sh ] && source _scripts/$PKG.inst_start.sh
fi

if [ "$1" = "end" ] && [ "$2" = "install-target" ]; then
    source $BUILDROOT/.package_source
    #NAME
    #VERSION
    #SOURCE_DIR

    ###overwrite
    [ "$PKG" = "glibc" ] && NAME="glibc"
    [ "$PKG" = "gcc" ] && NAME="gcc"
    ###overwrite

    ###overwrite
    [ ! -e _scripts/$PKG.rev ] && echo 1 > _scripts/$PKG.rev
    ###overwrite

    REV=`cat _scripts/$PKG.rev`
    [ -e _scripts/$PKG.ver ] && VERSION=`cat _scripts/$PKG.ver`

    if [ -e $DESTROOT/var/run ]; then
	echo "###### PKG_SCRIPT $PKG /var/run"
	if ! rmdir $DESTROOT/var/run 2> /dev/null; then
	    (ODIR=`pwd`; cd $DESTROOT/var/run && _mkcpio $ODIR/_scripts/$PKG@run.cpio)
	    rm -rf $DESTROOT/var/run 2> /dev/null
	    if [ ! -e _scripts/$PKG.inst_end.sh ]; then
		echo 'rm -rf $DESTROOT/var/run 2> /dev/null' > _scripts/$PKG.inst_end.sh
	    else
		FILE_END=`sh /bin/_file_end_linefeed.sh _scripts/$PKG.inst_end.sh`
		[ "$FILE_END" != "0a" ] && echo >> _scripts/$PKG.inst_end.sh
		! grep -qFx 'rm -rf $DESTROOT/var/run 2> /dev/null' _scripts/$PKG.inst_end.sh && \
		    echo 'rm -rf $DESTROOT/var/run 2> /dev/null' >> _scripts/$PKG.inst_end.sh
	    fi
	fi
    fi


    if [ -e $DESTROOT/usr/lib/perl5 ]; then
	if [ -e _scripts/perl.ver ]; then
	    PERL=`cat _scripts/perl.ver`
	    rm -f $DESTROOT/usr/lib/perl5/$PERL/x86_64-linux/perllocal.pod
	    find $DESTROOT/usr/lib/perl5/site_perl/$PERL/x86_64-linux/auto -name ".packlist" -type f | \
		xargs sed -i -n '/^\/usr\//p'
	fi
    fi

    rm -f $DESTROOT/usr/share/info/dir
    rm -f $DESTROOT/tools/share/info/dir

    rm $DESTROOT/usr/doc
    rm $DESTROOT/usr/man
    rm $DESTROOT/usr/info
    rm $DESTROOT/usr/lib64
    rm $DESTROOT/lib64
    for i in $CREATEDIRS; do
	rmdir $DESTROOT/$i 2> /dev/null
    done

    [ -e _scripts/$PKG.inst_end.sh ] && source _scripts/$PKG.inst_end.sh


    mkdir -p $DESTROOT/var/lib/instpkg/local
    mkdir -p $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV
    mkdir -p $DESTROOT/var/lib/instpkg/local/.local
    ln -sf ../$PKG-$VERSION-$REV $DESTROOT/var/lib/instpkg/local/.local/$PKG
    SIZE=`du -sk $DESTROOT | grep -o "^[0-9]\+"`
    echo -ne "NAME=$NAME\nVERSION=$VERSION\nREV=$REV\nDESC=\"\"\nSIZE=$SIZE\n" > $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV/info

    ###overwrite
    [ ! -e _scripts/$PKG.deps ] && touch _scripts/$PKG.deps
    ###overwrite

    sort -u _scripts/$PKG.deps > $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV/depends
    cat $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV/depends | tr '\n' ' ' | \
	sed 's% $%%' > $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV/depend@
    GRP=`grep "package.*/$PKG/Config.in" package/_pkgs.group@@@@ | cut -d " " -f 1-2`

    ###overwrite
    [ "$PKG" = "busybox" ] && GRP="base system"
    [ "$PKG" = "glibc" ] && GRP="base development"
    [ "$PKG" = "gcc" ] && GRP="base development"
    ###overwrite
    [ -z "$GRP" ] && GRP="unknown other"

    echo "$GRP" > $DESTROOT/var/lib/instpkg/local/$PKG-$VERSION-$REV/groups


    F_PASSWD="$BUILDROOT/tmp_passwd"
    F_GROUP="$BUILDROOT/tmp_group"

    if [ -e _scripts/$PKG.users ]; then
	if [ -e _scripts/$PKG.scr ]; then
	    FILE_END=`sh /bin/_file_end_linefeed.sh _scripts/$PKG.scr`
	    [ "$FILE_END" != "0a" ] && echo >> _scripts/$PKG.scr
	fi
	#
	echo -n > _scripts/$PKG.scr
	#
	cat _scripts/$PKG.users | \
	while read username uid group gid passwd home shell groups comment; do
	    if [ "$group" != "-" ]; then
		GRPID=`grep "^${group}:" "$F_GROUP" | cut -d : -f 3`
		[ -z "$GRPID" ] && echo "**Group not found: ${group}**" && continue
		if ! echo "$processed" | grep -q "^${group}$"; then
		    echo "#PRI#addgroup -g $GRPID $group 2> /dev/null" >> _scripts/$PKG.scr
		    echo "#POR#delgroup $group 2> /dev/null" >> _scripts/$PKG.scr
		    [ -z "$processed" ] && processed="$group" || processed=`echo -ne "$processed\n$group"`
		fi
	    fi
	    if [ "$groups" != "-" ]; then
		OIFS=$IFS
		IFS=$','
		for i in $groups; do
		    GRPID=`grep "^${i}:" "$F_GROUP" | cut -d : -f 3`
		    [ -z "$GRPID" ] && echo "**Group not found: ${group}**" && continue
		    if ! echo "$processed" | grep -q "^${i}$"; then
			echo "#PRI#addgroup -g $GRPID $i 2> /dev/null" >> _scripts/$PKG.scr
			echo "#POR#delgroup $i 2> /dev/null" >> _scripts/$PKG.scr
			[ -z "$processed" ] && processed="$i" || processed=`echo -ne "$processed\n$i"`
		    fi
		done
		IFS=$OIFS
	    fi
	done
	cat _scripts/$PKG.users | \
	while read username uid group gid passwd home shell groups comment; do
	    [ "$shell" != "-" ] && SHELL="-s $shell" || SHELL=
	    [ "$home" != "-" ] && HHOME="-h $home" || HHOME=
	    [ "$group" != "-" ] && GROUP="-G $group" || GROUP=
	    #[ "$comment" != "-" -a ! -z "$comment" ] && COMMENT="-g '$comment'" || COMMENT=
	    if [ "$username" != "-" ]; then
		USRID=`grep "^${username}:" "$F_PASSWD" | cut -d : -f 3`
		[ -z "$USRID" ] && echo "**User not found: ${username}**" && continue
		#echo "#PRI#adduser $HHOME $COMMENT $GROUP $SHELL -D -H -u $USRID $username 2> /dev/null" >> _scripts/$PKG.scr
		echo "#PRI#adduser $HHOME $GROUP $SHELL -D -H -u $USRID $username 2> /dev/null" >> _scripts/$PKG.scr
		echo "#POR#deluser $username 2> /dev/null" >> _scripts/$PKG.scr
		if [ "$groups" != "-" ]; then
		    OIFS=$IFS
		    IFS=$','
		    for i in $groups; do
			echo "#PRI#adduser $username $i 2> /dev/null" >> _scripts/$PKG.scr
			echo "#POR#delgroup $username $i 2> /dev/null" >> _scripts/$PKG.scr
		    done
		    IFS=$OIFS
		fi
	    fi
	done

    fi

    [ -d _scripts/files/$PKG/etc ] && cp -Rdp _scripts/files/$PKG/etc $DESTROOT

    (cd $DESTROOT; tar czf $PKGDEST/$PKG-$VERSION-$REV.tar.gz *)
    retval=$?
#
#    echo "$DONTINSTALL" | grep -q " $PKG " || tar xzf $PKGDEST/$PKG-$VERSION-$REV.tar.gz -C /
#
    rm -rf $DESTROOT/*

    rm -f $BUILDROOT/inst_start.log
fi
exit $retval
