#! /bin/bash

export LC_COLLATE=C
#get params: / targz / targz --root / targz --root dir /
[ -z "$1" ] && exit 1

ROOT=
[ "$2" = "--root" ] && ROOT=/
[ ! -z "$3" ] && ROOT="$3"
[ -z "$ROOT" ] && ROOT="."

[ ! -d "$ROOT" ] && echo "No such directory" && exit 1

OPWD=`pwd -P`
cd "$ROOT"
[ "$?" != 0 ] && echo "Cannot change to directory" && exit 1
ROOT=`pwd -P`
cd "$OPWD"
[ "$?" != 0 ] && echo "Cannot change to original directory" && exit 1

#setup tempfiles
tempfile1=`mktemp --suffix=-tmp1 2> /dev/null`
tempfile2=`mktemp --suffix=-tmp2 2> /dev/null`
tempfile3=`mktemp --suffix=-tmp3 2> /dev/null`
trap "rm -f $tempfile1 $tempfile2 $tempfile3" 0 1 2 5 15

#remove multiple slashes and slash from the end (to zero if ROOT=/)
ROOT=`echo -n "$ROOT" | sed -e 's%/\+$%%' -e 's%/\+%/%g'`

#cat list of directories to keep
[ -d "$ROOT"/var/lib/instpkg/local ] && removedb=1
keepdirs=`cat "$ROOT"/var/lib/instpkg/local/*/keepdirs 2> /dev/null | cut -d ' ' -f 4-`
#put root to prefix
[ ! -z "$keepdirs" ] && keepdirs=`echo "$keepdirs" | sed "s%.*%$ROOT/&/%"`

#list tar and add root dir and grep dirs
tar tzf "$1" | sed "s%.*%$ROOT/&%" | tee $tempfile1 | grep "/$" > $tempfile2

#grep files or links
grep -v "/$" $tempfile1 > $tempfile3

#rm files or links
cat $tempfile3 | tr '\n' '\0' | xargs -0 -r rm 2> /dev/null

#rm dirs
if [ "$removedb" = 1 ]; then
    tac $tempfile2 | grep -vFx "$keepdirs" | tr '\n' '\0' | xargs -0 -r rmdir 2> /dev/null
else
    tac $tempfile2 | tr '\n' '\0' | xargs -0 -r rmdir 2> /dev/null
fi
