#!/bin/sh

#pacman 3.5.4(and other) addon script
#template build (compile) file creator

[ -f PKGBUILD ] && exit 1

ARCHIVE=`find -maxdepth 1 -type f \( -name "*.tar.*" -o -name "*.tgz" \) -printf "%f\n" | sort | tail -n 1`

echo $ARCHIVE | grep -q "-" || exit 1
NAME=${ARCHIVE%-*}
[ $ARCHIVE != ${ARCHIVE%.tar.gz} ] && EXT=".tar.gz"
[ $ARCHIVE != ${ARCHIVE%.tar.bz2} ] && EXT=".tar.bz2"
[ $ARCHIVE != ${ARCHIVE%.tar.xz} ] && EXT=".tar.xz"
[ $ARCHIVE != ${ARCHIVE%.tgz} ] && EXT=".tgz"
NAME_WO_EXT=${ARCHIVE/%$EXT/}
VER=${NAME_WO_EXT/#$NAME-/}

cat > PKGBUILD << EOF
pkgname=$NAME
pkgver=$VER
pkgrel=1
pkgdesc="none"
source=(\$pkgname-\$pkgver$EXT)
md5sums=
arch=('i686')
license=('custom')
backup=
groups=('base' 'notset')
makedepends=
depends=('glibc')


build(){
cd \$srcdir/\$pkgname-\$pkgver
for i in \$(find \$startdir -maxdepth 1 -type f -name "*.patch" | sort); do
    echo "Applying patch: \$i"
    patch -p1 < \$i
done
[ -f \$startdir/patch/patch.sh ] && . \$startdir/patch/patch.sh


./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
make \$MKOPTS || return 1
make DESTDIR=\$pkgdir install


ls -dl \$pkgdir/usr/lib/python* 2> /dev/null | grep -q "^d" && \\
    echo "==============Using python ================"

if [ -d \$pkgdir/usr/lib/perl5 ]; then
    echo "==============Using perl5  ================"
fi
if [ -d \$pkgdir/usr/man ]; then
    echo "==============Moving man dir =============="
    mkdir -p \$pkgdir/usr/share
    mv \$pkgdir/usr/man \$pkgdir/usr/share
fi
if [ -d \$pkgdir/usr/info ]; then
    echo "==============Moving info dir=============="
    mkdir -p \$pkgdir/usr/share
    mv \$pkgdir/usr/info \$pkgdir/usr/share
fi
rm -f \$pkgdir/usr/share/info/dir
[ -d \$startdir/etc ] && cp -Rdp \$startdir/etc \$pkgdir
return 0
}
EOF
