#! /bin/bash
#coreutils
#--------compatible---------
#DEFAULT_POSIX2_VERSION=199209 ./configure --prefix=/tools
#--------not compatible-----
source ../009_
export FORCE_UNSAFE_CONFIGURE=1
./configure --prefix=/tools
make
make install
