#! /bin/bash
#e2fsprogs
source ../009_
mkdir build
cd build
../configure --prefix=/tools --enable-elf-shlibs
make
make install
make install-libs
#make DESTDIR=/dest install
#make DESTDIR=/dest install-libs
