#!/bin/sh

tempfile=`mktemp 2> /dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

cpiofile=file.cpio
[ ! -z "$1" ] && cpiofile=$1

find -mindepth 1 > $tempfile
cpio -o --format=newc < $tempfile > $cpiofile
