#! /bin/sh

: ${DIALOG=dialog}

tempfile=`mktemp 2> /dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

lsswappart()
{
for drv in $(find /dev -maxdepth 1 -name "[hs]d[a-z]" -o -name "ub[a-z]" | sort); do
    LC_ALL=C sfdisk -d $drv 2> /dev/null | grep "^/dev/" | \
    while read LINE; do
	if echo "$LINE" | grep -q "type=82"; then
	    echo -n "$(echo "$LINE" | cut -d : -f 1 | tr -d " ") "
	    eval $(echo "$LINE" | cut -d : -f 2 | cut -d , -f 2 | tr -d " ")
	    echo -n "$(expr $size \* 512 / 1048576)MB "
	fi
    done
done
}

$DIALOG --backtitle "Create swap on device" \
	--title "" --clear \
	--menu "Select partition" 20 61 15 \
	`lsswappart` 2> $tempfile

retval=$?

choice=`cat $tempfile`
case $retval in
    0)
	[ ! -z "$choice" ] && mkswap $choice
    ;;
    1)
	#cancel pressed
    ;;
    255)
	#ESC pressed
    ;;
esac
