#! /bin/sh

#2011 Raminos production (raminux.sf.net)

#group_expr [a-z0-9]\+
#pkgname_expr [a-zA-Z0-9_-+.]\+ (+version dependency string: "<>=")

tempdir=`mktemp -d 2> /dev/null` || tempdir=/tmp/tmpdir$$
tempdir2=`mktemp -d 2> /dev/null` || tempdir2=/tmp/tmpdir2$$
trap "rm -rf $tempdir $tempdir2" 0 1 2 5 15

[ "$1" = "local" ] && DATABASE=/var/lib/instpkg/packages.local.data || \
    DATABASE=/var/lib/instpkg/packages.data

[ ! -d /var/lib/instpkg ] && mkdir -p /var/lib/instpkg

[ ! -d $tempdir ] && mkdir -p $tempdir
[ ! -d $tempdir2 ] && mkdir -p $tempdir2


[ "$1" = "local" ] && cp -R /var/lib/pacman/local/* $tempdir || \
    tar xzf /var/lib/pacman/sync/core.db -C $tempdir

cd $tempdir

cat */desc > $tempdir2/pkgdata

#make packageinfo database
grep -A 2 "%GROUPS%" $tempdir2/pkgdata | grep -v "%GROUPS%\|^--$" | tr "\n" " " | \
    sed "s/[a-z0-9]\+ [a-z0-9]\+ /&#/g" | tr "#" "\n" | sed 's/ $//' > $tempdir2/groups
grep -A 1 "%NAME%" $tempdir2/pkgdata | grep -v "%NAME%\|^--$" > $tempdir2/names
grep -A 1 "%VERSION%" $tempdir2/pkgdata | grep -v "%VERSION%\|^--$" > $tempdir2/versions
[ "$1" = "local" ] && grep -A 1 "%SIZE%" $tempdir2/pkgdata | grep -v "%SIZE%\|^--$" > $tempdir2/sizes || \
    grep -A 1 "%ISIZE%" $tempdir2/pkgdata | grep -v "%ISIZE%\|^--$" > $tempdir2/sizes
grep -A 1 "%DESC%" $tempdir2/pkgdata | grep -v "%DESC%\|^--$" > $tempdir2/descriptions

NUMPKG=`wc -l $tempdir2/names | cut -d " " -f 1`
if [ $NUMPKG != `wc -l $tempdir2/descriptions | cut -d " " -f 1` ]; then
    for i in */desc; do grep -q "%DESC%" $i || echo -e "%DESC%\nnone\n\n" >> $i; done
    cat */desc > $tempdir2/pkgdata
    grep -A 1 "%DESC%" $tempdir2/pkgdata | grep -v "%DESC%\|^--$" > $tempdir2/descriptions
fi
if [ $NUMPKG != `wc -l $tempdir2/groups | cut -d " " -f 1` ]; then
    for i in */desc; do grep -q "%GROUPS%" $i || echo -e "%GROUPS%\nbase\nnotset\n\n" >> $i; done
    cat */desc > $tempdir2/pkgdata
    grep -A 2 "%GROUPS%" $tempdir2/pkgdata | grep -v "%GROUPS%\|^--$" | tr "\n" " " | \
	sed "s/[a-z0-9]\+ [a-z0-9]\+ /&#/g" | tr "#" "\n" | sed 's/ $//' > $tempdir2/groups
fi

paste -d ' ' $tempdir2/groups $tempdir2/names $tempdir2/versions $tempdir2/sizes $tempdir2/descriptions | sort > $DATABASE


#make dependency database
[ "$1" = "local" ] || cat */depends > $tempdir2/pkgdata

sed 's/%DEPENDS%/#DEPENDS#/g' $tempdir2/pkgdata | tr '\n' ' ' | sed -e 's/#DEPENDS#\( [a-zA-Z0-9_-+.<>=]\+\)\+/&#EDEPENDS#/g' \
    -e 's/#EDEPENDS#[^#]\+#DEPENDS#/#EDEPENDS##DEPENDS#/g' -e 's/^[^#]\+#DEPENDS#/#DEPENDS#/' \
    -e 's/#EDEPENDS#[^#]\+$/#EDEPENDS#/' -e 's/#EDEPENDS#/\n/g' > $tempdir2/depends

if [ $NUMPKG != `wc -l $tempdir2/depends | cut -d " " -f 1` ]; then
    [ "$1" = "local" ] && for i in */desc; do grep -q "%DEPENDS%" $i || echo -e "%DEPENDS%\nglibc\n\n" >> $i; done || \
	for i in */depends; do grep -q "%DEPENDS%" $i || echo -e "%DEPENDS%\nglibc\n\n" >> $i; done
    [ "$1" = "local" ] && cat */desc > $tempdir2/pkgdata || cat */depends > $tempdir2/pkgdata
    sed 's/%DEPENDS%/#DEPENDS#/g' $tempdir2/pkgdata | tr '\n' ' ' | sed -e 's/#DEPENDS#\( [a-zA-Z0-9_-+.<>=]\+\)\+/&#EDEPENDS#/g' \
	-e 's/#EDEPENDS#[^#]\+#DEPENDS#/#EDEPENDS##DEPENDS#/g' -e 's/^[^#]\+#DEPENDS#/#DEPENDS#/' \
	-e 's/#EDEPENDS#[^#]\+$/#EDEPENDS#/' -e 's/#EDEPENDS#/\n/g' > $tempdir2/depends
fi

#remove version dependency & put space to EOL
sed -i -e 's/.*/& /' -e 's/[<>=][=.0-9]\+ / /g' $tempdir2/depends

[ "$1" = "local" ] && paste -d ' ' $tempdir2/names $tempdir2/depends > /var/lib/instpkg/depends.local.data || \
    paste -d ' ' $tempdir2/names $tempdir2/depends > /var/lib/instpkg/depends.data

[ "$1" = "local" ] && ls /var/lib/pacman/local > /var/lib/instpkg/locallist.data
