#! /bin/bash

#check if files found in current dir and subdirs exists on destination dir and subdirs
[ ! -d "$1" ] && exit 1

find -type f -printf "%f\n" | \
while read file; do
if [ ! -z "$(find "$1" -type f -name "$file")" ]; then
    echo "$file"
fi
done
