#! /bin/sh

# _strip [-x /path_to/strip] [strip in directory]

if [ "$1" = "-x" ]; then
    # not default strip command
    shift

    if [ ! -z "$1" ]; then
	STRIP="$1"
	[ ! -e "$STRIP" ] && echo "No such strip command" && exit 1
    else
	echo "strip command should be specified" && exit 1
    fi
    shift
fi

if [ ! -z "$1" ]; then
    DIR="$1"
    [ ! -d "$DIR" ] && echo "No such directory" && exit 1
    cd "$DIR"
fi

[ -z "$STRIP" ] && STRIP=strip

find -type f -name "*.a" | \
while read file; do
    HEADER=`od -v -x -j 0 -N 7 "$file" 2> /dev/null | head -n 1 | cut -d ' ' -f 2-`
    [ "$HEADER" = "3c21 7261 6863 003e" ] && $STRIP -d "$file"
done

_findbin | xargs -r $STRIP -d
