#!/bin/sh

# $1 user
# $2 ttyN (without /dev)
[ -z "$1" -o -z "$2" ] && echo "usage: $0 user ttyN" && exit 1
[ "$(tty)" != "/dev/$2" ] && echo "use loginuser_openvt on other tty" && exit 1
exec env TTYPERM=620 login -f $1 < /dev/$2 > /dev/$2
