#! /bin/bash

listmods()
{
find /lib/modules/$LINVER/kernel/drivers/gpu/drm -mindepth 2 -type f -name "*.ko" 2> /dev/null | sed -e 's%.*/%%' -e 's/\.ko$//' | sort
}

listmods_gz()
{
find /lib/modules/$LINVER/kernel/drivers/gpu/drm -mindepth 2 -type f -name "*.ko.gz" 2> /dev/null | sed -e 's%.*/%%' -e 's/\.ko\.gz$//' | sort
}

procmods()
{
while read MOD; do
    if modinfo -k $LINVER $MOD | grep -q "^alias:"; then
	echo "$MOD"
    fi
done
}

LINVER="$1"
[ -z "$LINVER" ] && LINVER=`uname -r`
[ ! -d /lib/modules/$LINVER ] && exit 1

module=`head -n 1 /lib/modules/$LINVER/modules.dep | cut -d : -f 1`

[ "$(echo "$module" | sed 's/\.gz$//')" != "$module" ] && gz=1

[ $gz ] && listmods_gz | procmods || listmods | procmods
