#! /bin/bash

listmods()
{
(find /lib/modules/$LINVER/kernel/drivers/video/fbdev -type f -name "*.ko") 2> /dev/null | sed -e 's%.*/%%' -e 's/\.ko$//' | sort
}

procmods()
{
while read MOD; do
    if modinfo -k $LINVER $MOD | grep -q "^alias:"; then
	modinfo -k $LINVER $MOD | grep -q "^parm:[[:space:]]*mode_option" && echo "$MOD*" || echo "$MOD"
    fi
done
}

LINVER="$1"
[ -z "$LINVER" ] && LINVER=`uname -r`
[ ! -d /lib/modules/$LINVER ] && exit 1

listmods | procmods
