#! /bin/sh

echo "Unmounting /media devices"

pidof udisks-daemon > /dev/null 2>&1 && udisk=1
pidof udisksd > /dev/null 2>&1 && udisk2=1
if [ -z "$udisk" -a -z "$udisk2" ]; then
    find /media -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null | xargs -r -0 -i umount {}
else
    if [ -e /run/media ]; then
	find /run/media -mindepth 2 -maxdepth 2 -type d -print0 2> /dev/null | xargs -r -0 -i umount {}
    else
	if [ -e /media/`whoami` ]; then
	    find /media/`whoami` -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null | xargs -r -0 -i umount {}
	else
	    find /media -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null | xargs -r -0 -i umount {}
	fi
    fi
fi
