#!/bin/bash

set -e

main() {
    local pkgname="${1}"
    local pkgdep="${2}"
    [ ! -d _scripts ] && mkdir _scripts
    case "${pkgdep}" in
	busybox|skeleton|toolchain)
	;;
	host-automake|host-autoconf|host-libtool|host-tzdata)
	;;
	automake|autoconf|libtool)
	;;
	udev)
	    echo "eudev" >> _scripts/"${pkgname}.deps"
	;;
	jpeg)
	    echo "jpeg-turbo" >> _scripts/"${pkgname}.deps"
	;;
	python)
	    case "${pkgname}" in
		libxml2|libxslt)
		;;
		*)
		    echo "${pkgdep}" >> _scripts/"${pkgname}.deps"
		;;
	    esac
	;;
	#python-setuptools
	python-setuptools)
	    case "${pkgname}" in
		python-setuptools)
		;;
		*)
		    [ -e $BUILDROOT/.python_version ] && PYTHON_VER=`cat $BUILDROOT/.python_version`
		    if [ ! -z "$PYTHON_VER" -a "$PYTHON_VER" = 3 ]; then
			echo "${pkgdep}" | sed 's/^python-/python3-/' >> _scripts/"${pkgname}.deps"
		    else
			echo "${pkgdep}" >> _scripts/"${pkgname}.deps"
		    fi
		;;
	    esac
	;;
	python-*)
	    [ -e $BUILDROOT/.python_version ] && PYTHON_VER=`cat $BUILDROOT/.python_version`
	    if [ ! -z "$PYTHON_VER" -a "$PYTHON_VER" = 3 ]; then
		echo "${pkgdep}" | sed 's/^python-/python3-/' >> _scripts/"${pkgname}.deps"
	    else
		echo "${pkgdep}" >> _scripts/"${pkgname}.deps"
	    fi
	;;
	*)
	    echo "${pkgdep}" >> _scripts/"${pkgname}.deps"
	;;
    esac
}

BUILDROOT=output/build

main "${@}"
